### ISSUE TITLE
Great but how do I disable resizing the window also?

### ISSUE THREAD

**Issue by gerroon** [thinca/vim-fontzoom#2]
Hi

This plugin is cool however resizing the font also resizes and in some occasion undo full screen my Gvim window. Is there a way to make sure this does not happen?

thanks

**Comment by thinca** [comment]
Sorry, it is impossible.
In MS Windows, You can maximize a window of vim in `:simalt ~x`.
But, it isn't possible to get this state(maximized or not) from Vim script.  This can't be performed automatically.

**Comment by elig0n** [comment]
Well for anyone else who might be interested, I have found that at least for when GVim is maximized and on which it is the case where resize & arbitrary window relocation can get rather annoying, commenting [line 38 of fontzoom.vim](https://github.com/thinca/vim-fontzoom/blob/master/plugin/fontzoom.vim#L38)  (`let [&lines, &columns] = s:keep[2 :]`) prevents GVim from abruptly changing size and becoming a small window in a clutter, messing up layouts and destroying focus.
